<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>bulky_web</RootNamespace>
    <UserSecretsId>469f2426-287a-415d-9bd8-26d1f3b50b7a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.21">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Stripe.net" Version="50.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bulkt.DataAccess\Bulky.DataAccess.csproj" />
    <ProjectReference Include="..\Bulky.Utility\Bulky.Utility.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\product\" />
  </ItemGroup>

</Project>
